pass-gen-2
TahaBaber-devsinc/Password-generator pull request #1
Opened 2021-07-31 13:30 UTC by TahaBaber-devsinc

password genertor

2021-08-02 17:40 UTC, beinghaziq commented on pass_gen.arb
> +# password gen
make it more descriptive

2021-08-02 17:41 UTC, TahaBaber-devsinc commented on pass_gen.arb
> +# password gen
Noted

2021-08-02 17:41 UTC, beinghaziq commented on pass_gen.arb
> +    char_arr.flatten
Make them as constants. e.g. ALPHABETS = `[*('a'..'z'), *('A'..'Z')]`

2021-08-02 17:42 UTC, beinghaziq commented on pass_gen.arb
> +    len = Integer(gets, exception: false)
loop through them until user enter a valid value.

2021-08-02 17:44 UTC, beinghaziq requested changes
Added some comments

2021-08-02 19:01 UTC, beinghaziq approved these changes

2021-08-03 17:52 UTC, beinghaziq commented on pass_gen.arb
> +        len > 0 && len < 26 ? break : puts('Invalid input. Length should be between 1-25')
create constants for 0 and 26

2021-08-03 17:53 UTC, beinghaziq approved these changes
Conditionally approving

2021-08-03 17:55 UTC, merged